<?php

return [
    'colleges' => [
        'COLLEGE OF ARCHITECTURE AND FINE ARTS',
        'COLLEGE OF ENGINEERING',
        'COLLEGE OF INDUSTRIAL EDUCATION',
        'COLLEGE OF INDUSTRIAL TECHNOLOGY',
        'COLLEGE OF LIBERAL ARTS',
        'COLLEGE OF SCIENCE',
    ],
    'department_college_map' => [
        'Architecture Department' => 'COLLEGE OF ARCHITECTURE AND FINE ARTS',
        'Fine Arts Department' => 'COLLEGE OF ARCHITECTURE AND FINE ARTS',
        'Graphics Department' => 'COLLEGE OF ARCHITECTURE AND FINE ARTS',
        'Electrical Engineering' => 'COLLEGE OF ENGINEERING',
        'Electronics Communication Engineering' => 'COLLEGE OF ENGINEERING',
        'Mechanical Engineering' => 'COLLEGE OF ENGINEERING',
        'Civil Engineering' => 'COLLEGE OF ENGINEERING',
        'Student Teaching Department' => 'COLLEGE OF INDUSTRIAL EDUCATION',
        'Technical Arts Department' => 'COLLEGE OF INDUSTRIAL EDUCATION',
        'Home Economics Department' => 'COLLEGE OF INDUSTRIAL EDUCATION',
        'Professional Industrial Education' => 'COLLEGE OF INDUSTRIAL EDUCATION',
        'Basic Industrial Technology' => 'COLLEGE OF INDUSTRIAL TECHNOLOGY',
        'Civil Engineering Technology' => 'COLLEGE OF INDUSTRIAL TECHNOLOGY',
        'Food and Apparel Technology' => 'COLLEGE OF INDUSTRIAL TECHNOLOGY',
        'Graphic Arts and Printing Technology' => 'COLLEGE OF INDUSTRIAL TECHNOLOGY',
        'Mechanical Engineering Technology' => 'COLLEGE OF INDUSTRIAL TECHNOLOGY',
        'Power Plant Engineering Technology' => 'COLLEGE OF INDUSTRIAL TECHNOLOGY',
        'Languages Department' => 'COLLEGE OF LIBERAL ARTS',
        'Entrepreneurship and Management Department' => 'COLLEGE OF LIBERAL ARTS',
        'Social Science Department' => 'COLLEGE OF LIBERAL ARTS',
        'Physical Education' => 'COLLEGE OF LIBERAL ARTS',
        'Hospitality Management Department' => 'COLLEGE OF LIBERAL ARTS',
        'Mathematics Department' => 'COLLEGE OF SCIENCE',
        'Chemistry Department' => 'COLLEGE OF SCIENCE',
        'Physics Department' => 'COLLEGE OF SCIENCE',
        'Computer Studies Department' => 'COLLEGE OF SCIENCE',
    ],
];
