#!/usr/bin/env php
<?php

if (file_exists($a = __DIR__.'/vendor/autoload.php')) {
    require $a;
} else {
    require __DIR__.'/../../vendor/autoload.php';
}

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

exit($kernel->handle(new Symfony\Component\Console\Input\ArgvInput, new Symfony\Component\Console\Output\ConsoleOutput));
